version: '3.8'
services:
  gateway:
    build:
      context: ./Gateway
    ports:
      - "5000:80"
    depends_on:
      - orderservice
      - productservice

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5001:80"

  productservice:
    build:
      context: ./ProductService
    ports:
      - "5002:80"